### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by ghost** [aidanholm/mpv-easycrop#13]
Hi
The script doesn't seem to working. Could someone help me out?

**Comment by seaque** [comment]
[Try turning off hardware encoding. ](https://mpv.io/manual/master/#options-hwdec) I can tell from my experience it started to work after that. To disable hardware encoding at runtime, press Ctrl + h.

> Note that hardware decoding is in general not compatible with filters, and will therefore not work with this script.

Taken from https://github.com/occivink/mpv-scripts

**Comment by aidanholm** [comment]
Thank you for the pointer, seaque! 

I hope that was the issue, AhmedThahir66 -- if not, please reopen with more details about your set up, and I'll see what I can do

(and sorry for the very late response)
