### ISSUE TITLE
Doesn't seem to work anymore even with hwdec turned off

### ISSUE THREAD

**Issue by Trinity3e** [aidanholm/mpv-easycrop#15]
Hello, unfortunately in the latest versions of mpv it stopped working entirely.

**Comment by aidanholm** [comment]
Thanks for reporting! Are there any error messages or other log output when trying to activate cropping mode? This is still working fine for me on the current latest version of 0.35.0

**Comment by Trinity3e** [comment]
My apologies, i tried again now and it does work fine.

I think an other script was conflicting or i had hwdec on in gpu-next (took me a while to figure out that 'hwdec=no' is now used in gpu-next instead of 'hwdec=none/off', the legacy option will silently error for some reason).
